version: '3.8'
services:
  config-server:
    build:
      context: config-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8888:8888"
    networks:
      - currency-network

  netflix-zuul-api:
      build:
        context: zuul
        dockerfile: Dockerfile
      restart: always
      ports:
        - "8765:8765"
      networks:
        - currency-network
      depends_on:
        - config-server
        - eureka-server

  eureka-server:
      build:
        context: eureka
        dockerfile: Dockerfile
      restart: on-failure
      ports:
        - "8761:8761"
      networks:
        - currency-network

  conversion-service:
    build:
      context: conversion
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8080"
    networks:
      - currency-network
    depends_on:
      - config-server
      - eureka-server
      - exchange-service
      - netflix-zuul-api

  exchange-service:
    build:
      context: exchange
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9090:9090"
    networks:
      - currency-network
    depends_on:
      - config-server
      - eureka-server
      - netflix-zuul-api

networks:
  currency-network:
