spring:
  application:
    name: netflix-zuul-api
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: rabbitmq
server:
  port: 8765
management:
  endpoints:
    web:
      base-path: /manage
      expose:
        include: "*"
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
user:
  role: Developer
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
zuul:
  prefix: /api
  routes:
    exchange-service:
      path: /exchange/**
      service-id: exchange-service
    convert-service:
      path: /convert/**
      service-id: convert-service
  host:
    socket-timeout-millis: 7200000
feign:
  client:
    config:
      default:
        connectionTimeout: 5000
        readTimeout: 6000
ribbon:
  connectionTimeout: 6000
  ReadTimeout: 6000



